#!/usr/bin/env python3
"""Compile Wayfarer's pixel-art atlas and space texture into native RGB565."""

from pathlib import Path
import struct
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "source"
DEST = ROOT / "main"


def packed(image: Image.Image, transparent: bool = False) -> list[int]:
    rgba = image.convert("RGBA").tobytes()
    result = []
    for i in range(0, len(rgba), 4):
        r, g, b, a = rgba[i : i + 4]
        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        result.append(0 if transparent and a < 128 else max(1, value))
    return result


def main() -> None:
    sheet = Image.open(SOURCE / "space-sprites-pixel.png").convert("RGBA")
    x_edges = [round(sheet.width * i / 3) for i in range(4)]
    y_edges = [round(sheet.height * i / 2) for i in range(3)]
    specs = [
        ("freighter", (x_edges[0], y_edges[0], x_edges[1], y_edges[1]), 108),
        ("courier", (x_edges[1], y_edges[0], x_edges[2], y_edges[1]), 86),
        ("tanker", (x_edges[2], y_edges[0], x_edges[3], y_edges[1]), 106),
        ("planet", (x_edges[0], y_edges[1], x_edges[1], y_edges[2]), 138),
        ("moon", (x_edges[1], y_edges[1], x_edges[2], y_edges[2]), 56),
        ("asteroid", (x_edges[2], y_edges[1], x_edges[3], y_edges[2]), 30),
    ]
    header = [
        "/* SPDX-License-Identifier: GPL-3.0-only */\n/* Generated by tools/compile_assets.py. */",
        "#pragma once",
        "#include <stdint.h>",
        "typedef struct { int width, height; const uint16_t *pixels; } wayfarer_sprite_t;",
        "typedef struct { uint16_t left, right; } wayfarer_span_t;",
        "extern const uint16_t wayfarer_span_rows[241];",
        "extern const wayfarer_span_t wayfarer_window_spans[];",
        "extern const uint16_t wayfarer_lamp_rows[241];",
        "extern const uint16_t wayfarer_lamp_x[];",
        "enum { WAYFARER_SKY_WIDTH = 512, WAYFARER_SKY_HEIGHT = 128 };",
        "extern const uint8_t wayfarer_sky[512 * 128];",
        "extern const uint16_t wayfarer_sky_palettes[17 * 256];",
    ]
    code = [
        "/* SPDX-License-Identifier: GPL-3.0-only */\n/* Generated by tools/compile_assets.py. */",
        '#include "assets_generated.h"',
    ]

    def array(name: str, values: list[int], static: bool = False, bits: int = 16) -> None:
        code.append(f"{'static ' if static else ''}const uint{bits}_t {name}[{len(values)}] = {{")
        code.extend(
            "    " + ",".join(f"0x{v:0{bits // 4}x}" for v in values[i : i + 16]) + ","
            for i in range(0, len(values), 16)
        )
        code.append("};")

    previews = Image.new("RGBA", (320, 230))
    for index, (name, bounds, width) in enumerate(specs):
        cutout = sheet.crop(bounds)
        alpha = cutout.getchannel("A").point(lambda a: 255 if a >= 128 else 0)
        bbox = alpha.getbbox()
        if not bbox:
            raise RuntimeError(f"empty sprite: {name}")
        cutout = cutout.crop(bbox)
        height = max(1, round(cutout.height * width / cutout.width))
        logical_width = max(1, width // 2)
        logical_height = max(1, height // 2)
        cutout = cutout.resize((logical_width, logical_height), Image.Resampling.LANCZOS)
        alpha = cutout.getchannel("A").point(lambda a: 255 if a >= 128 else 0)
        colors = cutout.convert("RGB").quantize(
            colors=40, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE
        )
        cutout = colors.convert("RGB").convert("RGBA")
        cutout.putalpha(alpha)
        cutout = cutout.resize((width, height), Image.Resampling.NEAREST)
        # Preserve a hard silhouette and crisp 2x pixel clusters on the LCD.
        cutout.putalpha(cutout.getchannel("A").point(lambda a: 255 if a >= 128 else 0))
        array(f"pixels_{name}", packed(cutout, True), True)
        code.append(
            f"const wayfarer_sprite_t wayfarer_{name} = {{{width}, {height}, pixels_{name}}};"
        )
        header.append(f"extern const wayfarer_sprite_t wayfarer_{name};")
        previews.paste(cutout, (index % 2 * 160, index // 2 * 76), cutout)
        print(f"{name}: {width}x{height}")
    sky = Image.open(SOURCE / "space-pixel.png").convert("RGB")
    target_ratio = 4.0
    if sky.width / sky.height > target_ratio:
        crop_width = round(sky.height * target_ratio)
        left = (sky.width - crop_width) // 2
        sky = sky.crop((left, 0, left + crop_width, sky.height))
    else:
        crop_height = round(sky.width / target_ratio)
        top = (sky.height - crop_height) // 2
        sky = sky.crop((0, top, sky.width, top + crop_height))
    sky = sky.resize((256, 64), Image.Resampling.LANCZOS)
    sky = sky.quantize(colors=48, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    sky = sky.resize((512, 128), Image.Resampling.NEAREST)
    array("wayfarer_sky", list(sky.tobytes()), bits=8)
    palette = sky.getpalette()
    palette += [0] * (768 - len(palette))
    shades = []
    for level in range(17):
        for index in range(256):
            r, g, b = palette[index * 3 : index * 3 + 3]
            r, g, b = (channel * (16 + level) // 32 for channel in (r, g, b))
            shades.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))
    array("wayfarer_sky_palettes", shades)
    cockpit = struct.unpack("<128640H", (DEST / "assets" / "cockpit.rgb565").read_bytes())
    span_rows, lamp_rows, spans, lamps = [], [], [], []
    for y in range(240):
        span_rows.append(len(spans))
        lamp_rows.append(len(lamps))
        left = None
        for x in range(536):
            color = cockpit[y * 536 + x]
            if not color and left is None:
                left = x
            if left is not None and (color or x == 535):
                spans.append((left, x if color else 536))
                left = None
            r, g, b = color >> 11, (color >> 5) & 63, color & 31
            if r >= 25 and 18 <= g < 53 and b < 12:
                lamps.append(x)
    span_rows.append(len(spans))
    lamp_rows.append(len(lamps))
    array("wayfarer_span_rows", span_rows)
    array("wayfarer_lamp_rows", lamp_rows)
    array("wayfarer_lamp_x", lamps)
    code.append(f"const wayfarer_span_t wayfarer_window_spans[{len(spans)}] = {{")
    code.extend(f"    {{{left}, {right}}}," for left, right in spans)
    code.append("};")
    print(f"canopy: {len(spans)} spans; illuminated lamp pixels: {len(lamps)}")
    (DEST / "assets_generated.h").write_text("\n".join(header) + "\n")
    (DEST / "assets_generated.c").write_text("\n".join(code) + "\n")
    previews.save(ROOT / "preview-assets.png")
    sky.save(ROOT / "preview-space.png")


if __name__ == "__main__":
    main()
