#pragma once
#include <stdint.h>

typedef struct { uint8_t width, height; const uint8_t *pixels; } dungeon_sprite_t;
enum dungeon_sprite_id {
    DSP_WALL_NEAR,
    DSP_WALL_MID,
    DSP_WALL_FAR,
    DSP_CEILING_NEAR,
    DSP_CEILING_MID,
    DSP_CEILING_FAR,
    DSP_FLOOR_NEAR,
    DSP_FLOOR_MID,
    DSP_FLOOR_FAR,
    DSP_ARCH,
    DSP_DOOR,
    DSP_TORCH,
    DSP_BANNER,
    DSP_CHAIN,
    DSP_SKULLS,
    DSP_RUBBLE,
    DSP_ROOTS,
    DSP_CHEST,
    DSP_SHRINE,
    DSP_GATE,
    DSP_SKELETON_0,
    DSP_SKELETON_1,
    DSP_SKELETON_2,
    DSP_SKELETON_3,
    DSP_SLIME_0,
    DSP_SLIME_1,
    DSP_SLIME_2,
    DSP_SLIME_3,
    DSP_BRUTE_0,
    DSP_BRUTE_1,
    DSP_BRUTE_2,
    DSP_BRUTE_3,
    DSP_EYE_0,
    DSP_EYE_1,
    DSP_EYE_2,
    DSP_EYE_3,
    DSP_WARDEN_0,
    DSP_WARDEN_1,
    DSP_WARDEN_2,
    DSP_WARDEN_3,
    DSP_WYRM_0,
    DSP_WYRM_1,
    DSP_WYRM_2,
    DSP_WYRM_3,
    DSP_ELDRITCH_0,
    DSP_ELDRITCH_1,
    DSP_ELDRITCH_2,
    DSP_ELDRITCH_3,
    DSP_SWORD,
    DSP_STAFF,
    DSP_HANDS,
    DSP_SLASH,
    DSP_BOLT,
    DSP_IMPACT,
    DSP_BURST,
    DSP_TITLE,
    DSP_COUNT
};
extern const uint16_t dungeon_palette[16];
extern const dungeon_sprite_t dungeon_sprites[DSP_COUNT];
