#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Allocate each firmware image the minimum contiguous number of 64 KiB blocks."""

import argparse
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
BLOCK_SIZE = 64 * 1024
FLASH_SIZE = 16 * 1024 * 1024
APP_START = 0x20000
# Labels and OTA subtypes are stable even when image growth moves their addresses.
IMAGES = (
    ("factory", "factory", "build/multi_pin_launcher.bin"),
    ("conways", "ota_0", "firmwares/conways-pin/build/conways_pin.bin"),
    ("fluid", "ota_1", "firmwares/fluid-pin/build/fluid_pin.bin"),
    ("miso", "ota_2", "firmwares/pet-pin/build/miso_pin.bin"),
    ("lumen", "ota_3", "firmwares/render-pin/build/lumen_pin.bin"),
    ("dungeon", "ota_4", "firmwares/dungeon-pin/build/dungeon_seed.bin"),
    ("maze", "ota_5", "firmwares/maze-pin/build/maze_pin.bin"),
    ("wayfarer", "ota_6", "firmwares/wayfarer-pin/build/wayfarer_pin.bin"),
    ("threebody", "ota_7", "firmwares/three-body-pin/build/three_body_pin.bin"),
    ("crt", "ota_8", "firmwares/crt-pin/build/crt_pin.bin"),
)


def allocate(root):
    """Return (label, subtype, path, offset, capacity, image_size) entries."""
    entries = []
    offset = APP_START
    for label, subtype, relative_path in IMAGES:
        path = root / relative_path
        size = path.stat().st_size
        if size == 0:
            raise ValueError(f"Empty firmware image: {path}")
        capacity = ((size + BLOCK_SIZE - 1) // BLOCK_SIZE) * BLOCK_SIZE
        if offset + capacity > FLASH_SIZE:
            raise ValueError(f"{label} exceeds the board's 16 MiB flash capacity")
        entries.append((label, subtype, path, offset, capacity, size))
        offset += capacity
    return entries


def render_csv(entries):
    lines = [
        "# Generated by tools/app_layout.py from built firmware images.",
        "# Each app occupies one contiguous partition of ceil(image_size / 64 KiB) blocks.",
        "# Name, Type, SubType, Offset, Size, Flags",
        "nvs, data, nvs, 0x9000, 0x6000,",
        "otadata, data, ota, 0xf000, 0x2000,",
    ]
    for label, subtype, _, offset, capacity, _ in entries:
        lines.append(f"{label}, app, {subtype}, {offset:#x}, {capacity:#x},")
    return "\n".join(lines) + "\n"


def check_layout(root, entries, compiled=False):
    if (root / "partitions.csv").read_text() != render_csv(entries):
        raise ValueError("partitions.csv is stale; run ./build-and-flash.sh --build-only")
    if not compiled:
        return
    # Check the actual table which will be flashed, not only its CSV source.
    expected = [("nvs", 1, 2, 0x9000, 0x6000), ("otadata", 1, 0, 0xF000, 0x2000)]
    for label, subtype, _, offset, capacity, _ in entries:
        number = 0 if subtype == "factory" else 0x10 + int(subtype[4:])
        expected.append((label, 0, number, offset, capacity))
    table = (root / "build/partition_table/partition-table.bin").read_bytes()
    actual = []
    for position in range(0, len(table), 32):
        record = table[position : position + 32]
        if len(record) != 32:
            raise ValueError("Truncated compiled partition table")
        magic, kind, subtype, offset, capacity, label, flags = struct.unpack("<HBBII16sI", record)
        if magic != 0x50AA:
            break  # MD5 record or end padding.
        if flags:
            raise ValueError("Unexpected flags in compiled partition table")
        actual.append((label.rstrip(b"\0").decode(), kind, subtype, offset, capacity))
    if actual != expected:
        raise ValueError("Compiled partition table is stale; rebuild the launcher before flashing")


def report(entries):
    print("Partition       Image bytes  64 KiB blocks  Capacity KiB  Offset")
    for label, _, _, offset, capacity, size in entries:
        print(
            f"{label:<15} {size:>11} {capacity // BLOCK_SIZE:>14} {capacity // 1024:>13}  {offset:#x}"
        )
    end = entries[-1][3] + entries[-1][4]
    print(
        f"Unallocated flash: {FLASH_SIZE - end:,} bytes ({(FLASH_SIZE - end) / 1024 / 1024:.4f} MiB)"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("projects", "generate", "check", "flash-args"))
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument(
        "--compiled", action="store_true", help="also check the built binary partition table"
    )
    args = parser.parse_args()
    root = args.root.resolve()
    if args.command == "projects":
        for _, _, relative_path in IMAGES[1:]:
            print((root / relative_path).parent.parent)
        return
    try:
        entries = allocate(root)
        if args.command == "generate":
            path = root / "partitions.csv"
            content = render_csv(entries)
            if not path.exists() or path.read_text() != content:
                path.write_text(content)
            report(entries)
        else:
            check_layout(root, entries, compiled=args.compiled or args.command == "flash-args")
            if args.command == "flash-args":
                for _, _, path, offset, _, _ in entries[1:]:
                    print(f"{offset:#x}")
                    print(path)
            else:
                report(entries)
    except (OSError, ValueError) as error:
        parser.exit(1, f"Layout error: {error}\n")


if __name__ == "__main__":
    main()
