/* SPDX-License-Identifier: GPL-3.0-only */
/* Generated by tools/compile_assets.py. */
#pragma once
#include <stdint.h>
typedef struct { int width, height; const uint16_t *pixels; } wayfarer_sprite_t;
typedef struct { uint16_t left, right; } wayfarer_span_t;
extern const uint16_t wayfarer_span_rows[241];
extern const wayfarer_span_t wayfarer_window_spans[];
extern const uint16_t wayfarer_lamp_rows[241];
extern const uint16_t wayfarer_lamp_x[];
enum { WAYFARER_SKY_WIDTH = 512, WAYFARER_SKY_HEIGHT = 128 };
extern const uint8_t wayfarer_sky[512 * 128];
extern const uint16_t wayfarer_sky_palettes[17 * 256];
extern const wayfarer_sprite_t wayfarer_freighter;
extern const wayfarer_sprite_t wayfarer_courier;
extern const wayfarer_sprite_t wayfarer_tanker;
extern const wayfarer_sprite_t wayfarer_planet;
extern const wayfarer_sprite_t wayfarer_moon;
extern const wayfarer_sprite_t wayfarer_asteroid;
